author = Riccardo "Jack" Lucchetti
email = r.lucchetti@univpm.it
version = 1.9
date = 2025-02-08
description = heatmap and contour plots
tags = C10
min-version = 2021a
data-requirement = no-data-ok
gui-main = heatmap_GUI
label = Heatmap
menu-attachment = MAINWIN/View
public = heatmap heatmap_func heatmap_GUI
no-print = heatmap_func heatmap_GUI
help = heatmap_help.md
gui-help = gui_help.md
sample-script = heatmap_sample.inp
data-files = examples
